ALTER TABLE workout_plans
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ARCHIVED';

ALTER TABLE workout_plans
    ADD COLUMN created_at TIMESTAMP DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();